### ISSUE TITLE
期待する機能

### ISSUE THREAD

**Issue by book000** [JourneyHQ/DynmapProcessor#1]
- 引数を受け付ける (ハイフンのパラメータとかを取れるようなライブラリ使えばいいかな)
  - タイル画像の場所を指定
  - 出力先ファイルパスを指定
  - 出力画像サイズを指定
  - ズームサイズの指定
- Dynmapのタイル画像を組み合わせて、1枚の大きなマップ画像にする
- 画像を出力する
  - リサイズ: 特定の画像サイズに変更する
  - クリップ: 特定のエリアのみ切り出す
- マップ画像の上に、四角・線・丸などを書き込める機能
  - 線の場合は2点の位置をx,z座標として引数で渡される
  - 四角の場合は各角の位置をx,z座標として引数で渡される
  - 四角の場合は被せ色を指定することで四角内をその色で被せるようなやつ。[こんなかんじ](https://cdn.discordapp.com/attachments/854283647687065612/880672959801475072/file.png)
  - 引数じゃなくても、JSONかなにかで書かれた独自のマーカーファイル的なものを作ってそれのファイルパスを引数で渡させてもいい。その方が使いやすいかな？わからん

**Comment by yuuahp** [comment]
![image](https://user-images.githubusercontent.com/53546237/226078518-8481ee74-6b86-4ba9-8152-376435d67d98.png)

やらかしました。

**Comment by book000** [comment]
仕方なし。変な人が流入しないことを願いましょう…
